### ISSUE TITLE
Salsa did not write scaffolds_FINAL.fasta

### ISSUE THREAD

**Issue by fg6** [machinegun/SALSA#16]
Hi,
I am trying to run Salsa on a mouse (2.7 GB), but it did not write the final scaffolds fasta.
I am running using the following command:

$  python run_pipeline.py -a  data/M_musculus_129_v1.assembly.fasta -l data/M_musculus_129_v1.assembly.fasta.fai -b salsa/create_bed/bwa.bed -e DpnII -o scaffolds 

I don't get any errors, and the last file written is contig_links_scaled_sorted_iteration_2.
If I check the scaffold_length_iteration_2, the n50 is identical to the original fasta, I guess this means
that no links and no scaffolds have been made, and as a consequence the scaffolds_FINAL.fasta is not printed out?
Below more details.

Thank you very much,
Francesca

The files I get are:
   alignment_iteration_1.bed  breakpoints_iteration_2.txt	contig_links_iteration_2   
   contig_links_scaled_sorted_iteration_1  misasm_2.DONE re_counts_iteration_2 scaffolds_iteration_1.p 
   alignment_iteration_2.bed  commands.log	contig_links_scaled_iteration_1   
   contig_links_scaled_sorted_iteration_2  misasm_iteration_2.report  scaffold_length_iteration_1 
   assembly.cleaned.fasta   contig_links_iteration_1 contig_links_scaled_iteration_2  
   links_avoid_iteration_2	 re_counts_iteration_1  scaffold_length_iteration_2

The output was:

> python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/RE_sites.py -a scaffolds/assembly.cleaned.fasta -e DpnII > scaffolds/re_counts_iteration_1
> Starting Iteration 1
> python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/make_links.py -b scaffolds/alignment_iteration_1.bed -d scaffolds -i 1 -x abc
> bedfile started
> bedfile loaded
> python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/fast_scaled_scores.py -d scaffolds -i 1
> sort -k 5 -gr scaffolds/contig_links_scaled_iteration_1 > scaffolds/contig_links_scaled_sorted_iteration_1
> python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/layout_unitigs.py -x abc -u abc -t abc -l scaffolds/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d scaffolds
> Loading Hi-C links 
> Finished loading Hi-C links, Loading unitig links now..
> Hybrid scaffold graph loaded, nodes = 5412 edges = 2724
> Hi-C implied edges = 0
> Unitig tiling implied edges = 0
> Assembly graph implied edges = 0
> 10x implied edges = 0
> /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/break_contigs -a scaffolds/alignment_iteration_2.bed -b scaffolds/breakpoints_iteration_2.txt -l scaffolds/scaffold_length_iteration_2 -i 2 > scaffolds/misasm_iteration_2.report
> python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/refactor_breaks.py -d scaffolds -i 2
> Starting Iteration 2
> python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/make_links.py -b scaffolds/alignment_iteration_2.bed -d scaffolds -i 2
> bedfile started
> bedfile loaded
> Starting Iteration 2

**Comment by machinegun** [comment]
Hi,

For the -e option, you need the enter the actual sequence rather than name
of the enzyme. If you enter the nucleotide sequence for DpnII, if would
work.

On Dec 14, 2017 5:21 AM, "Francesca Giordano" <notifications@github.com>
wrote:

Hi,
I am trying to run Salsa on a mouse (2.7 GB), but it did not write the
final scaffolds fasta.
I am running using the following command:

$ python run_pipeline.py -a data/M_musculus_129_v1.assembly.fasta -l
data/M_musculus_129_v1.assembly.fasta.fai -b salsa/create_bed/bwa.bed -e
DpnII -o scaffolds

I don't get any errors, and the last file written is
contig_links_scaled_sorted_iteration_2.
If I check the scaffold_length_iteration_2, the n50 is identical to the
original fasta, I guess this means
that no links and no scaffolds have been made, and as a consequence the
scaffolds_FINAL.fasta is not printed out?
Below more details.

Thank you very much,
Francesca

The files I get are:
alignment_iteration_1.bed breakpoints_iteration_2.txt
contig_links_iteration_2
contig_links_scaled_sorted_iteration_1 misasm_2.DONE re_counts_iteration_2
scaffolds_iteration_1.p
alignment_iteration_2.bed commands.log contig_links_scaled_iteration_1
contig_links_scaled_sorted_iteration_2 misasm_iteration_2.report
scaffold_length_iteration_1
assembly.cleaned.fasta contig_links_iteration_1
contig_links_scaled_iteration_2
links_avoid_iteration_2 re_counts_iteration_1 scaffold_length_iteration_2

The output was:

python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/RE_sites.py -a
scaffolds/assembly.cleaned.fasta -e DpnII > scaffolds/re_counts_iteration_1
Starting Iteration 1
python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/make_links.py
-b scaffolds/alignment_iteration_1.bed -d scaffolds -i 1 -x abc
bedfile started
bedfile loaded
python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/fast_scaled_scores.py
-d scaffolds -i 1
sort -k 5 -gr scaffolds/contig_links_scaled_iteration_1 >
scaffolds/contig_links_scaled_sorted_iteration_1
python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/layout_unitigs.py
-x abc -u abc -t abc -l scaffolds/contig_links_scaled_sorted_iteration_1 -c
1000 -i 1 -d scaffolds
Loading Hi-C links
Finished loading Hi-C links, Loading unitig links now..
Hybrid scaffold graph loaded, nodes = 5412 edges = 2724
Hi-C implied edges = 0
Unitig tiling implied edges = 0
Assembly graph implied edges = 0
10x implied edges = 0
/lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/break_contigs -a
scaffolds/alignment_iteration_2.bed -b scaffolds/breakpoints_iteration_2.txt
-l scaffolds/scaffold_length_iteration_2 -i 2 >
scaffolds/misasm_iteration_2.report
python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/refactor_breaks.py
-d scaffolds -i 2
Starting Iteration 2
python /lustre/scratch117/sciops/team117/hpag/fg6/bin/SALSA/make_links.py
-b scaffolds/alignment_iteration_2.bed -d scaffolds -i 2
bedfile started
bedfile loaded
Starting Iteration 2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/machinegun/SALSA/issues/16>, or mute the thread

**Comment by fg6** [comment]
Thank you,
I will try again!


Cheers,
Francesca
