### ISSUE TITLE
Using SALSA2 in conjunction with Chicago data

### ISSUE THREAD

**Issue by chad388** [machinegun/SALSA#23]
Hi,

I noticed in your recent publication that you used Chicago data in conjunction with SALSA2.
Did you need to make any modifications to the Chicago data prior to using it with SALSA2 or were you able to use it directly?

Best,
Chad

**Comment by machinegun** [comment]
We just used the bed file for Chicago reads alignment.

On Mar 20, 2018 6:53 PM, "chad388" <notifications@github.com> wrote:

Hi,

I noticed in your recent publication that you used Chicago data in
conjunction with SALSA2.
Did you need to make any modifications to the Chicago data prior to using
it with SALSA2 or were you able to use it directly?

Best,
Chad

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/machinegun/SALSA/issues/23>, or mute the thread

**Comment by chad388** [comment]
Thanks for the details.

Best,
Chad
