### ISSUE TITLE
when I use this tools ,I met a mistakes,I need some help.

### ISSUE THREAD

**Issue by hzaumsq** [machinegun/SALSA#52]
python /public/tools/SALSA/run_pipeline.py -a polsih.fasta -l polsih.fasta.fai -b temp1.bed -e GATC -o scaffolds1 -m yes
bedfile loaded
Traceback (most recent call last):
  File "/public/msq/tools/SALSA/correct.py", line 69, in <module>
    oline += str(contig2new[attrs[0]] +'\t'+attrs[1]+'\t'+attrs[2]+'\t'+attrs[3]+'\n')
KeyError: '000017FP01'

mv: cannot stat ‘scaffolds1//asm.cleaned.fasta’: No such file or directory

**Comment by machinegun** [comment]
Looks like the binaries for c++ code have not been generated. Did you run`make` after cloning the repo?

**Comment by hzaumsq** [comment]
Ok,Thank you ,I have solved this problem. But I have another question,when I run SALAs,it's appear the following information,I can't understang it‘s meaning .
Hybrid scaffold graph loaded, nodes = 96 edges = 72
Hi-C implied edges = 0
Starting Iteration 3
bedfile started
bedfile loaded
Starting Iteration 3
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 74 edges = 56
Hi-C implied edges = 0
Starting Iteration 4
bedfile started
bedfile loaded
Starting Iteration 4
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 38 edges = 28

what is "nodes" and "edges" behalfs? and when I found many short scaffold(<1Mb) in my finaly resunt，if I didn't konw the number of chromosomes?  What should I choose??

**Comment by baishengjun** [comment]
Hi，

I met the same probelm, how to slove it?

Thanks,
Bai

**Comment by skoren** [comment]
@hzaumsq salsa doesn't need a chromosome count to be specified. The nodes/edges are the links found in the HiC data. They aren't parameters you can specify. You will end up with shorter unscaffolded things in your data, salsa is relatively conservative in its scaffolding and will stop when it detects that useful joins aren't being made. 

@baishengjun not sure what error you're referring to, the initial issue was due to not compiling the program when it was installed. Have you run make?
