### ISSUE TITLE
it generates too many scaffold in the result

### ISSUE THREAD

**Issue by zhangxiner2** [machinegun/SALSA#60]
hello,
when I run the software with generating the result. But it generates 3553 scaffold(too many) in the final result. 
which parameter can I set to get a better result?

my command line likes this :
python2 ./run_pipeline.py -a ONTmin.fasta -l ONTmin.fasta.fai -b ONT.sort.REduced.paired_only.bed -e AAGCTT -o scaffolds

I would appreciate it if you answer me as soon as possible.

**Comment by harish0201** [comment]
Hi,

I'm having the same issue with two plant genomes I'm working on currently. I have the BNG scaffolded sequences on which I'm running SALSA2 and the number of scaffolds are nearly similar.

For example genome 1, The terms Q1..3 are the interquartile ranges of the genome assemblies.


Assembly | Optical Map | Hi-C Scaffolds
-- | -- | --
num_seqs  | 4724 | 4023
Assembly Length | 830327566 | 827920466
min_len | 60 | 60
avg_len |  175767.9 | 205796.8
max_len | 12011242 | 26000256
Q1 | 19081 | 17602
Q2 | 33469 | 29414
Q3 | 74932 | 53863
N50 | 1359972 | 6895190

I don't think coverages should be issue because I do have about 67x based on stats from bamstats.

The other question being, how many times should I set the iterations? Currently it is set to 5 times, will SALSA2 autodetect?

 The following is the log:

bedfile loaded

Starting Iteration 1
bedfile started
bedfile loaded
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 2894 edges = 2034
Hi-C implied edges = 0
Starting Iteration 2
bedfile started
bedfile loaded
Starting Iteration 2
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 1444 edges = 854
Hi-C implied edges = 0
Starting Iteration 3
bedfile started
bedfile loaded
Starting Iteration 3
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 1432 edges = 794
Hi-C implied edges = 0
Starting Iteration 4
bedfile started
bedfile loaded
Starting Iteration 4
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 1548 edges = 840
Hi-C implied edges = 0
python /apps/assembly/hic/SALSA/RE_sites.py -a genome1/iter//assembly.cleaned.fasta -e GATC,GANTC > genome1/iter//re_counts_iteration_1
python /apps/assembly/hic/SALSA/make_links.py -b genome1/iter//alignment_iteration_1.bed -d genome1/iter/ -i 1 -x abc
python /apps/assembly/hic/SALSA/fast_scaled_scores.py -d genome1/iter/ -i 1
sort -k 5 -gr genome1/iter//contig_links_scaled_iteration_1 > genome1/iter//contig_links_scaled_sorted_iteration_1
python /apps/assembly/hic/SALSA/layout_unitigs.py -x abc -l genome1/iter//contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d genome1/iter/
/apps/assembly/hic/SALSA/break_contigs -a genome1/iter//alignment_iteration_2.bed -b genome1/iter//breakpoints_iteration_2.txt -l genome1/iter//scaffold_length_iteration_2 -i 2 -s 100   > genome1/iter//misasm_iteration_2.report
python /apps/assembly/hic/SALSA/refactor_breaks.py -d genome1/iter/ -i 2
python /apps/assembly/hic/SALSA/make_links.py -b genome1/iter//alignment_iteration_2.bed -d genome1/iter/ -i 2
python /apps/assembly/hic/SALSA/layout_unitigs.py -x abc -l genome1/iter//contig_links_scaled_sorted_iteration_2 -c 1000 -i 2 -d genome1/iter/
/apps/assembly/hic/SALSA/break_contigs -a genome1/iter//alignment_iteration_3.bed -b genome1/iter//breakpoints_iteration_3.txt -l genome1/iter//scaffold_length_iteration_3 -i 3 -s 100  > genome1/iter//misasm_iteration_3.report
python /apps/assembly/hic/SALSA/refactor_breaks.py -d genome1/iter/ -i 3 > genome1/iter//misasm_3.log
python /apps/assembly/hic/SALSA/make_links.py -b genome1/iter//alignment_iteration_3.bed -d genome1/iter/ -i 3
python /apps/assembly/hic/SALSA/layout_unitigs.py -x abc -l genome1/iter//contig_links_scaled_sorted_iteration_3 -c 1000 -i 3 -d genome1/iter/
/apps/assembly/hic/SALSA/break_contigs -a genome1/iter//alignment_iteration_4.bed -b genome1/iter//breakpoints_iteration_4.txt -l genome1/iter//scaffold_length_iteration_4 -i 4 -s 100  > genome1/iter//misasm_iteration_4.report
python /apps/assembly/hic/SALSA/refactor_breaks.py -d genome1/iter/ -i 4 > genome1/iter//misasm_4.log
python /apps/assembly/hic/SALSA/make_links.py -b genome1/iter//alignment_iteration_4.bed -d genome1/iter/ -i 4
python /apps/assembly/hic/SALSA/layout_unitigs.py -x abc -l genome1/iter//contig_links_scaled_sorted_iteration_4 -c 1000 -i 4 -d genome1/iter/
/apps/assembly/hic/SALSA/break_contigs -a genome1/iter//alignment_iteration_5.bed -b genome1/iter//breakpoints_iteration_5.txt -l genome1/iter//scaffold_length_iteration_5 -i 5 -s 100  > genome1/iter//misasm_iteration_5.report
python /apps/assembly/hic/SALSA/refactor_breaks.py -d genome1/iter/ -i 5 > genome1/iter//misasm_5.log

**Comment by machinegun** [comment]
Yes, SALSA autodetects the correct number of iterations given the HiC data alignments. Do you have any expectation of what should be the scaffold sizes?

**Comment by harish0201** [comment]
For one of the cases it should be 20-30Mbp and the other it should be between 40-75Mbp.

**Comment by ViriatoII** [comment]
I am also struggling with this. The results were not satisfactory and I forced a higher iterations number (also 8).  The N50 and L90 became very good, but how do I know this is correct? 

Are more iterations going to introduce errors? 2 years ago this relevant question remained open:
https://github.com/machinegun/SALSA/issues/13#issue-254729278

**Comment by ViriatoII** [comment]
I have created contact probability heatmaps with Juicer for two runs of Salsa: 
1)  With automatic parameters
![SSPACE_SALSA_uncleaned_it4_auto](https://user-images.githubusercontent.com/25958099/55387548-e7123780-5531-11e9-80fd-f5e66bf45a19.png)
2) Forcing 8 iterations with -i 8
![SSPACE_SALSA_uncleaned_it4_iter](https://user-images.githubusercontent.com/25958099/55387539-e24d8380-5531-11e9-8036-a301c083972c.png)

It appears to me that forcing more iterations gives better results.

**Comment by harish0201** [comment]
I checked the input scaffold lengths for my other genome. Scaffolds length (50 such scaffolds) less than 1000bp contribute to less than 25kb, the rest 408Mb are greater than those.
