### ISSUE TITLE
I can not get the scaffolds.fasta

### ISSUE THREAD

**Issue by okokookk** [machinegun/SALSA#9]
I made the alignment_unique.bed, contig_length_new, new_links_sorted and RE_counts files.
There are 32 lines in the new_links_sorted file.
And then, I run the command :
python links_to_graph3.py -a assembled_contigs.fa -f scaffolds.fasta -l new_links_sorted -n contig_length_new -o scaffold.agp -c 1 > paths

But, the result files (ambigous_contigs, paths, scaffold.agp, scaffolds.fasta) are empty.
How can I get the fasta file containing final scaffolds?

**Comment by machinegun** [comment]
How does you contig name look like? Does it have ':' in it?

**Comment by okokookk** [comment]
No, ':' is not included in the contig name.

**Comment by machinegun** [comment]
Can you copy few lines from new_links_sorted file here?

**Comment by okokookk** [comment]
Contig385312:E Contig385343:E 0.0122922222222 1
Contig1168168:E Contig1168183:E 0.00615 1
Contig116069:E Contig116098:E 0.00300272727273 1
Contig347071:E Contig347104:E 0.00265333333333 1
Contig213246:E Contig213262:E 0.00230743410236 1
Contig188867:E Contig188872:E 0.002235 1
Contig486790:E Contig486815:E 0.00160666666667 1
Contig73329:E Contig73346:E 0.00155333333333 1
Contig470135:E Contig470205:E 0.00150333333333 1
Contig1015:E Contig1020:E 0.00141642146031 1

**Comment by machinegun** [comment]
What is the first line of thr file? I want to see highest number of hic
links shared between any two contigs.

**Comment by okokookk** [comment]
"Contig385312:E Contig385343:E 0.0122922222222 1" is the first line.

**Comment by machinegun** [comment]
Strange. The #hi-c links shared is just 1. What was the coverage fro Hi-C data you used?

**Comment by okokookk** [comment]
Oh, that is 1x depth. The above analysis results were just tests. :)

I tried to analyze the Hi-c data of 54x again, however, I couldn't get a correct result.
The analysis was conducted as following:

First, the paired-end reads of my sample were aligned to the assembled contigs using BWA-MEM with default options. And then, the rmdup command of SAMtools and  GATK IndelRealigner were applied. 
After obtaining the bam file, I created the "alignment_unique.bed", "assembled_contigs.fa.fai", "contig_length_new" and "RE_counts" files.

And then, I ran the following command, but, I got an empty "new_links" file. 
python new_links.py -b alignment_unique.bed -c RE_counts -l contig_length_new > new_links
Do you have any idea what the problem may be?

I tried a different method because it was failed to get a correct result.
I mapped each individual fastq file using BWA-aln, and I used the BWA sampe.
After that, the each bam file was merged, and samtools rmdup was applied.

When I ran "new_links.py", I got the following results.

Contig831175:E Contig831183:E 0.00098 1
Contig872209:E Contig872210:E 0.000305184285136 1
Contig824087:E Contig824097:E 0 1
Contig1954:E Contig1955:E 0 1

I don't know what's the matter. Help me please.

**Comment by machinegun** [comment]
What is your contig N50? Based on that you would need to set some parameters.

**Comment by okokookk** [comment]
The contig N50 is 26Mb.

**Comment by machinegun** [comment]
Try using create_links1.py code with same params.

**Comment by peterdfields** [comment]
I am getting similar results, but in addition to an empty scaffolds.fasta file I'm also observing all of the following files being empty:

```
new_links
new_links_sorted
paths
scaffold.agp
```

**Comment by machinegun** [comment]
Can you please check if the bed file is sorted by read name? Also is there
any ':' present in your contig names?

**Comment by peterdfields** [comment]
The sorting of the bam file by coordinate instead of name was the issue, thanks!

**Comment by weirdlobster** [comment]
Hello, I am running into the same issue. Just to clarify, does sorting the BAM file avoid this problem or sorting the BED file?

I sorted my SAM file, converted to BAM, and I am still only having a single scaffold as output.

My BED file is sorted by contig name.

What files do I need to delete to continue?

**Comment by machinegun** [comment]
You need to sort the bed file by `read name` not the `contig name`.  Once you have bam file, you can run `samtools sort` with `-n` option. Then you can convert the resulting output into bed file and use for scaffolding.

**Comment by weirdlobster** [comment]
Just to clarify, if I have the correct BED file and I invoke run.py, will it use this BED file and continue to run the script?

**Comment by machinegun** [comment]
If you delete everything else from the directory (just keep the bed file).

**Comment by weirdlobster** [comment]
I believe I have done all that. Here is the processing I had to do to get a BED sorted by reads:

samtools sort -n -o ./hic_sorted.sam -T temp ./hic.sam
samtools view -bS ./hic_sorted.sam > ./hic_sorted.bam
bedtools bamtobed -i ./hic_sorted.bam
##changed the name of the bed file to alignment_unique.bed
and this is the top of the file:

c_000000003787  962     1012    M00626:286:000000000-AW2A6:1:1101:1724:15600/1  60      -
c_000000011689  3333    3383    M00626:286:000000000-AW2A6:1:1101:1724:15600/2  60      +
c_000000013362  653     703     M00626:286:000000000-AW2A6:1:1101:1795:15845/1  0       -
c_000000002268  7980    8030    M00626:286:000000000-AW2A6:1:1101:1795:15845/2  60      -
c_000000005972  704     754     M00626:286:000000000-AW2A6:1:1101:1800:14716/2  60      -
c_000000002849  1556    1605    M00626:286:000000000-AW2A6:1:1101:1826:16535/1  60      -
c_000000002849  1378    1420    M00626:286:000000000-AW2A6:1:1101:1826:16535/2  60      +
c_000000006147  5817    5867    M00626:286:000000000-AW2A6:1:1101:1831:16614/1  60      +
c_000000006147  6124    6168    M00626:286:000000000-AW2A6:1:1101:1831:16614/2  60      -
c_000000009344  208     258     M00626:286:000000000-AW2A6:1:1101:1903:15914/1  60      -

So it is sorted by reads...

I deleted everything but my BED file and wrapper script to run salsa, and this is my directory after running it again:


-rw-rw-r-- 1 weirdlob weirdlob  45M Sep 22 12:02 alignment_unique.bed
-rw-rw-r-- 1 weirdlob weirdlob    0 Sep 22 12:03 ambigous_contigs
-rw-rw-r-- 1 weirdlob weirdlob 125K Sep 22 12:03 contig_length_new
-rw-rw-r-- 1 weirdlob weirdlob  352 Sep 22 09:57 create.sh
-rw-rw-r-- 1 weirdlob weirdlob    0 Sep 22 12:03 new_links
-rw-rw-r-- 1 weirdlob weirdlob    0 Sep 22 12:03 new_links_sorted
-rw-rw-r-- 1 weirdlob weirdlob    0 Sep 22 12:03 paths
-rw-rw-r-- 1 weirdlob weirdlob 119K Sep 22 12:03 RE_counts
-rw-rw-r-- 1 weirdlob weirdlob  348 Sep 22 11:43 runsalsa1.sh
-rw-rw-r-- 1 weirdlob weirdlob  310 Sep 22 11:21 runsalsa.sh
-rw-rw-r-- 1 weirdlob weirdlob  362 Sep 22 12:03 salsaerr
-rw-rw-r-- 1 weirdlob weirdlob   40 Sep 22 12:03 salsaout
-rw-rw-r-- 1 weirdlob weirdlob    0 Sep 22 12:03 scaffold.agp
-rw-rw-r-- 1 weirdlob weirdlob    0 Sep 22 12:03 scaffolds.fasta

It looks like it is crashing at the new_links portion.

**Comment by machinegun** [comment]
Can you paste the error log? If `new_links` file is empty and error log does not specify any error, it may be possible that the data is low coverage and there are not enough links for scaffolding.

**Comment by weirdlobster** [comment]
Error file:


Module slurm/16.05.5 loaded
Module bio/1.0 loaded
Module salsa/f49f4d6 loaded
Currently Loaded Modulefiles:
  1) slurm/16.05.5   2) bio/1.0         3) salsa/f49f4d6
finished conversion
started generating links between contigs
bedfile started
bedfile loaded
done generating links between contigs
started scaffolding
done scaffolding, sequences written to file

**Comment by weirdlobster** [comment]
I'm working on a small genome, approx 30Mb. My BED file sorted by contig showed 10-20 reads mapped to each contig.

**Comment by weirdlobster** [comment]
I think my BAM file needed some sorting/filtering, but my scaffolding is still failing past one scaffold.

Just to be clear, I took my original SAM file, sorted it by read, then filtered out any unmapped, unpaired reads:
samtools view -h -F 4
samtools view -h -F 8
samtools view -b -h -f 1
The final file was a BAM file with the header included (I also tried no header), and all reads that mapped and had a pair. After starting the pipeline again, my BED file looked like this:

c_000000005489  7539    7587    M00626:286:000000000-AW2A6:1:2106:16453:1407/1  0       +
c_000000003398  10914   10964   M00626:286:000000000-AW2A6:1:2106:16453:1407/2  60      +
c_000000015746  482     527     M00626:286:000000000-AW2A6:1:2106:16190:1418/1  60      -
c_000000005040  5111    5150    M00626:286:000000000-AW2A6:1:2106:16190:1418/2  2       -
c_000000008412  2360    2410    M00626:286:000000000-AW2A6:1:2106:16922:1446/1  60      -
c_000000008412  2133    2183    M00626:286:000000000-AW2A6:1:2106:16922:1446/2  60      -
c_000000008123  2741    2791    M00626:286:000000000-AW2A6:1:2106:14712:1492/1  60      -
c_000000007879  2658    2708    M00626:286:000000000-AW2A6:1:2106:14712:1492/2  60      +
c_000000021870  2037    2087    M00626:286:000000000-AW2A6:1:2106:16372:1531/1  60      -
c_000000016985  2891    2941    M00626:286:000000000-AW2A6:1:2106:16372:1531/2  60      +
c_000000006360  245     295     M00626:286:000000000-AW2A6:1:2106:17852:1619/1  60      +
c_000000006114  7069    7119    M00626:286:000000000-AW2A6:1:2106:17852:1619/2  60      -
c_000000010717  2223    2273    M00626:286:000000000-AW2A6:1:2106:13073:1632/1  60      +
c_000000010717  2393    2436    M00626:286:000000000-AW2A6:1:2106:13073:1632/2  60      -
c_000000012926  3219    3269    M00626:286:000000000-AW2A6:1:2106:14924:1648/1  60      +
c_000000028496  1618    1667    M00626:286:000000000-AW2A6:1:2106:14924:1648/2  60      +
c_000000003631  3262    3303    M00626:286:000000000-AW2A6:1:2106:17215:1690/1  60      +
c_000000003371  8650    8678    M00626:286:000000000-AW2A6:1:2106:17215:1690/2  0       +

Giving me the impression this part was correct. Since this is where the original thread found success in their problem, I believe I'm running into a different issue now. Here is the SAM version of my BAM file, with the header cut off except for the top 3, showing my sorting and filtering. I've added returns to aid in reading.

@SQ     SN:c_000000006584       LN:6889
@SQ     SN:c_000000003056       LN:12732
@PG     ID:bwa  PN:bwa  VN:0.7.9a-r786  CL:bwa mem -P -k 17 -U 0 -L 0,0 -T 25 /home/weirdlob/l3agenome/bowtie/L3A-contigs.fa /home/weirdlob/Trim/trimmomatic/HiCdatal3a/shorttrim/outpaired1.fq /home/weirdl
ob/Trim/trimmomatic/HiCdatal3a/shorttrim/outpaired2.fq

M00626:286:000000000-AW2A6:1:2106:16425:1348    113     c_000000019377  2069    60      50M     c_000000014623  3021    0       CTTGAGCGGTACGATCGGCTCAGACTTGGTGGGTTTGTCGTCATCAGCTC      BGD?GGEFGHG2CE?EGF5D
5HGGA4DGGFECGFECECABD5FD4AA3AA      NM:i:0  MD:Z:50 AS:i:50 XS:i:0

M00626:286:000000000-AW2A6:1:2106:16425:1348    177     c_000000014623  3021    42      50M     c_000000019377  2069    0       TGTTTTTTTTTGTTTTTTTTGTTTTTTTTTTTTGTTTTTTTTGTTTTGTT      HE</?EGFCFGE/CEEGEAF
1EEE?2GGGGFGCGGF?GFFAAF?F@BABB      NM:i:0  MD:Z:50 AS:i:50 XS:i:38

M00626:286:000000000-AW2A6:1:2106:16453:1407    65      c_000000005489  7540    0       48M2S   c_000000003398  10915   0       GCTTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTAAATGCGTTTTTCCTGA      BB3AACDBFAAAEEAEEE?F
GFFC//E@E//E@/B2B22//?>FA22222      NM:i:2  MD:Z:33T3T10    AS:i:38 XS:i:35

M00626:286:000000000-AW2A6:1:2106:16453:1407    129     c_000000003398  10915   60      50M     c_000000005489  7540    0       CTGAAGAAGACCGTACCGTCTGGTTCTACCGCGACGTCCAAGGACTCAAT      >AAAADDFCFFFA1AE1A0E
00CD11AGHHE?E/EEEEF/1FFHFGBGHF      NM:i:0  MD:Z:50 AS:i:50 XS:i:0

M00626:286:000000000-AW2A6:1:2106:16190:1418    113     c_000000015746  483     60      45M5S   c_000000005040  5112    0       AAAAAGAAAAAAGAAAAGAAACACGAGACAGTGATGCATCAATTCAGATT      HHHFHCEFHHHHGHHHF54H
FHFGFDEDFGGFGGFFGDDFFBFD5ABBBA      NM:i:0  MD:Z:45 AS:i:45 XS:i:17

M00626:286:000000000-AW2A6:1:2106:16190:1418    177     c_000000005040  5112    2       11S39M  c_000000015746  483     0       GGGACACTTTTTTTTTTTTTTTTTTTTTTTTTTTTGCTACATGGTGCTGA      112211/<@?@EE//>G@E0
ECCEEEECGGGFGFGFBB5FD4?FD??AA3      NM:i:0  MD:Z:39 AS:i:39 XS:i:37

M00626:286:000000000-AW2A6:1:2106:16922:1446    113     c_000000008412  2361    60      50M     =       2134    -228    TCTAGTGACTCACCTCTTCGGTCGGTTCACGGGATGTTCGAGAGAGAGTG      GHGHHHHHFHHHHHGGGGGGGFFHHFEE
GCGGGGGGGGBFFFFFFBBBBB      NM:i:0  MD:Z:50 AS:i:50 XS:i:0

M00626:286:000000000-AW2A6:1:2106:16922:1446    177     c_000000008412  2134    60      50M     =       2361    228     GCAAGCATCCGGCGGTGACTTGCAGATGCAGATGATGTAGGTACCGATAC      HHHFHGE?GGGFDGGFHEECHGGHHFHG
FGGGGGGFGFBFAAABBBBAA>      NM:i:1  MD:Z:29C20      AS:i:45 XS:i:0

M00626:286:000000000-AW2A6:1:2106:14712:1492    81      c_000000008123  2742    60      50M     c_000000007879  2659    0       ACAGCAACAACAACACACTCCCCGGGGCTGCACCAGCTGACATCAAAGCT      1GAFFAAA/0GFAA1B///A
0CGFEFA11GFFBF1B3GD@FFBB31AAAA      NM:i:1  MD:Z:20A29      AS:i:45 XS:i:17

M00626:286:000000000-AW2A6:1:2106:14712:1492    161     c_000000007879  2659    60      50M     c_000000008123  2742    0       ATCGATACAGCGAGATTGAGAGATTATATAGAGTAGGTAGACATACAAAA      A?AAA11A@@FD11A0BGGG
0CFH11FGFFCAGFGHH121DGGFHHHHF0      NM:i:0  MD:Z:50 AS:i:50 XS:i:0

Here is my directory as well:

total 41M
-rw-rw-r-- 1 weirdlob weirdlob  31M Sep 23 10:05 alignment_unique.bed
-rw-rw-r-- 1 weirdlob weirdlob    0 Sep 23 10:05 ambigous_contigs
-rw-rw-r-- 1 weirdlob weirdlob 125K Sep 23 10:05 contig_length_new
-rw-rw-r-- 1 weirdlob weirdlob 5.3M Sep 23 10:05 new_links
-rw-rw-r-- 1 weirdlob weirdlob 5.3M Sep 23 10:05 new_links_sorted
-rw-rw-r-- 1 weirdlob weirdlob   81 Sep 23 10:05 paths
-rw-rw-r-- 1 weirdlob weirdlob 119K Sep 23 10:05 RE_counts
-rwxrwxrwx 1 weirdlob weirdlob  301 Sep 23 10:04 runsalsa.sh
-rw-rw-r-- 1 weirdlob weirdlob  432 Sep 23 10:05 salsaerr
-rw-rw-r-- 1 weirdlob weirdlob   40 Sep 23 10:05 salsaout
-rw-rw-r-- 1 weirdlob weirdlob  191 Sep 23 10:05 scaffold.agp
-rw-rw-r-- 1 weirdlob weirdlob  20K Sep 23 10:05 scaffolds.fasta

Please let me know if I could show anything else from my files to assist. I've been very hopeful to get SALSA to work because I have had issues with other Hi-C software.

**Comment by machinegun** [comment]
A couple of things: Is your new_links file empty? If its not then you probably need to change some cutoffs:

In the file linkstograph3.py, on line 142, you can change this if count < 150:. Currently, it would consider links only with hic links more than 150.
Alternatively, you can take a look at the code in 'iterative salsa' branch. We have made some changes to the initial version of the code. In that code, you won't have to set any cutoffs.

**Comment by weirdlobster** [comment]
That may be it, as the Hi-C data is not high coverage. My new links file is 5.3Mb.

What do you recommend changing it to? Or would you recommend iterative salsa to bypass this.

**Comment by machinegun** [comment]
I would recommend using iterative pipeline.

**Comment by weirdlobster** [comment]
Thank you for the recommendation, the iterative salsa script created scaffolds. My coverage ended up not being sufficient for the main pipeline, but the iterative was able to use my Hi-C data to scaffold. Thanks again!

**Comment by ardy20** [comment]
Could you please guide where is the iterative pipeline?
